/*
  使用方法：调用分库分表sql生成器SqlGenerator生成
 */
drop database if exists gworders;
CREATE database gworders DEFAULT CHARACTER SET utf8;

create table gworders.GW_ORDERS
(
  order_id            bigint(64) not null,
  service             VARCHAR(64) not null,
  merchant_order_no   VARCHAR(128) not null,
  merchant_id         VARCHAR(22) not null,
  seller_name         VARCHAR(100) not null,
  seller_id           VARCHAR(22) not null,
  buyer_name          VARCHAR(100),
  buyer_id            VARCHAR(22),
  seller_remarks      VARCHAR(512),
  buyer_remarks       VARCHAR(512),
  buyer_realname      VARCHAR(32),
  buyer_contact       VARCHAR(64),
  price               DECIMAL not null,
  query_key           VARCHAR(64),
  quantity            DECIMAL not null,
  sign_type           VARCHAR(10) not null,
  charsets            VARCHAR(10) not null,
  currency            VARCHAR(4) not null,
  order_date          VARCHAR(14) not null,
  exp_dates           VARCHAR(5) not null,
  ips                 VARCHAR(20) not null,
  ordersts            VARCHAR(64) not null,
  return_url          VARCHAR(512),
  notify_url          VARCHAR(512),
  subject             VARCHAR(256) not null,
  bodys               VARCHAR(512) not null,
  amount              DECIMAL not null,
  price_changed       DECIMAL(1),
  api_version         VARCHAR(20),
  locale              VARCHAR(10) not null,
  preference          VARCHAR(25),
  refund_amount       DECIMAL(19),
  refund_sts          VARCHAR(10),
  order_type          VARCHAR(3) not null,
  pay_method          VARCHAR(10),
  service_fee         DECIMAL,
  agentid             VARCHAR(22),
  close_date_time     datetime,
  show_url            VARCHAR(512),
  token_id            VARCHAR(100),
  member_ip           VARCHAR(30),
  terminal_info       VARCHAR(100),
  terminal_type       VARCHAR(64),
  business_id         VARCHAR(6),
  product_type        VARCHAR(100),
  result_code         VARCHAR(6),
  result_msg          VARCHAR(64),
  modify_date_time    datetime,
  modify_user_id      VARCHAR(20),
  delete_flag         VARCHAR(1),
  create_date_time    datetime not null,
  create_user_id      VARCHAR(20),
  product_category_id VARCHAR(20),
  product_id          VARCHAR(20),
  api_type            VARCHAR(20),
  member_id           VARCHAR(50),
  refund_amount_sure  DECIMAL,
  protocol_no         VARCHAR(50),
  bind_id             VARCHAR(50),
  card_type           VARCHAR(2),
  identify_flag       VARCHAR(2),
  charge_purpose      VARCHAR(1),
  sms_check           VARCHAR(1),
  device_id           VARCHAR(50),
  discount_amount     DECIMAL,
  real_amount         DECIMAL,
  PRIMARY KEY (order_id )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;